### ISSUE TITLE
Improve `Usage` documentation for all components

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/dnn-elements#999]
Improve `Usage` documentation for all components.  Within StencilJS is a convention for documentation that allows individual usage examples to be located within a `usage` folder for each component.  The file name is used as a title for each example within the `Usage` section of the component auto-generated portion of the `readme.md`.  For now, we can stick with the following two usage example filenames:
* HTML.md
* JSX-TSX.md

Using ALL CAPS seems to keep the titles from translating to Title Case.

```[tasklist]
### Tasks
- [ ] Implement `Usage` documentation for `dnn-button`
- [ ] Implement `Usage` documentation for `dnn-checkbox`
- [ ] Implement `Usage` documentation for `dnn-chevron`
- [ ] Implement `Usage` documentation for `dnn-collapsible`
- [ ] Implement `Usage` documentation for `dnn-color-input`
- [ ] Implement `Usage` documentation for `dnn-color-picker`
- [ ] Implement `Usage` documentation for `dnn-dropzone`
- [ ] Implement `Usage` documentation for `dnn-image-cropper`
- [ ] Implement `Usage` documentation for `dnn-input`
- [ ] Implement `Usage` documentation for `dnn-modal`
- [ ] Implement `Usage` documentation for `dnn-monaco-editor`
- [ ] Implement `Usage` documentation for `dnn-permissions-grid`
- [ ] Implement `Usage` documentation for `dnn-progress-bar`
- [ ] Implement `Usage` documentation for `dnn-richtext`
- [ ] Implement `Usage` documentation for `dnn-searchbox`
- [ ] Implement `Usage` documentation for `dnn-select`
- [ ] Implement `Usage` documentation for `dnn-sort-icon`
- [ ] Implement `Usage` documentation for `dnn-tab`
- [ ] Implement `Usage` documentation for `dnn-tabs`
- [ ] Implement `Usage` documentation for `dnn-toggle`
- [ ] Implement `Usage` documentation for `dnn-treeview-item`
- [ ] Implement `Usage` documentation for `dnn-vertical-overflow-menu`
- [ ] Implement `Usage` documentation for `dnn-vertical-splitview`
```
